### ISSUE TITLE
Compiler errors killing build on MacOS

### ISSUE THREAD

**Issue by headius** [rake-compiler/rake-compiler-dock#18]
Cryptic "internal compiler error" kills build of the ffi gems for Windows when building on MacOS. I'm not sure what to do about this.

```
x86_64-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:241: recipe for target 'Call.o' failed
make: *** [Call.o] Error 4
make: *** Waiting for unfinished jobs....
x86_64-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:241: recipe for target 'AbstractMemory.o' failed
make: *** [AbstractMemory.o] Error 4
x86_64-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:241: recipe for target 'ArrayType.o' failed
make: *** [ArrayType.o] Error 4
x86_64-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:241: recipe for target 'Buffer.o' failed
make: *** [Buffer.o] Error 4
../../../../ext/ffi_c/Function.c: In function 'async_cb_event':
../../../../ext/ffi_c/Function.c:563:9: warning: implicit declaration of function 'rb_thread_call_without_gvl' [-Wimplicit-function-declaration]
         rb_thread_call_without_gvl(async_cb_wait, &w, async_cb_stop, &w);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../ext/ffi_c/Function.c: In function 'callback_prep':
../../../../ext/ffi_c/Function.c:948:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
     ffiStatus = ffi_prep_closure(code, &fnInfo->ffi_cif, callback_invoke, closure);
     ^~~~~~~~~
In file included from ../../../../ext/ffi_c/Function.c:51:0:
/Users/headius/projects/ffi/build/x64-mingw32/ffi_c/2.5.0/libffi-x64-mingw32/include/ffi.h:314:1: note: declared here
 ffi_prep_closure (ffi_closure*,
 ^~~~~~~~~~~~~~~~
../../../../ext/ffi_c/MethodHandle.c: In function 'prep_trampoline':
../../../../ext/ffi_c/MethodHandle.c:151:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
     ffiStatus = ffi_prep_closure(code, &mh_cif, attached_method_invoke, closure);
     ^~~~~~~~~
In file included from ../../../../ext/ffi_c/MethodHandle.c:53:0:
/Users/headius/projects/ffi/build/x64-mingw32/ffi_c/2.5.0/libffi-x64-mingw32/include/ffi.h:314:1: note: declared here
 ffi_prep_closure (ffi_closure*,
 ^~~~~~~~~~~~~~~~
x86_64-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:241: recipe for target 'Function.o' failed
make: *** [Function.o] Error 4
rake aborted!
Command failed with status (2): [nice make -j...]
/usr/local/rvm/gems/ruby-2.4.3/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:166:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.4.3/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:165:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => native => native:x64-mingw32 => native:ffi:x64-mingw32 => build/x64-mingw32/stage/lib/2.5/ffi_c.so => copy:ffi_c:x64-mingw32:2.5.0 => build/x64-mingw32/ffi_c/2.5.0/ffi_c.so
(See full trace by running task with --trace)
```

**Comment by larskanis** [comment]
I can not reproduce this issue - probably because I don't have MacOS. Nevertheless I just released rake-compiler-dock-0.6.3 with updated base image. So you could re-try it? But wait - it's still uploading to docker hub...
